import type { NextPage } from "next";
import Head from "next/head";
import { useAllPokemonsQuery } from "generated/pokemons_graphql";
import PokemonTable from "@components/PokemonsTable";

const Root: NextPage = () => {
  const allPokemonsQuery = useAllPokemonsQuery();

  let PokemonsDisplay = null;
  if (allPokemonsQuery.error) PokemonsDisplay = "error";
  else if (allPokemonsQuery.data)
    PokemonsDisplay = (
      <PokemonTable pokemons={allPokemonsQuery.data.pokemons} />
    );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {PokemonsDisplay}
    </>
  );
};

export default Root;
