import Home from './home'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Box } from '@mui/material'

const Root: NextPage = () => {
  return (
    <Box sx={{minHeight: '100vh'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home/>
    </Box>
  )
}

export default Root
